In [1]:
import numpy as np
a = np.array([[1, 2, 3, 3, 1],[6, 8, 11, 10, 7]]).T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [2]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

In [3]:
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [80]:
a_centered_sp = np.dot((a[:,1:].T),(a[:,:1]))
a_centered_sp / (a.shape[0]-1)

array([[23.]])

In [83]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])

По какой-то причине показатели не сошлись